### ISSUE TITLE
Send one notification per transaction when there are multiple registrations promoted from Wait list status

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-wait-lists#11]
Reported here:

https://eventespresso.com/topic/waiting-list-manager-multiple-notification/

One idea I thought of would be to change the Registration Promoted From Wait List Notification message type (and others like it) to use the Primary Registrant context instead. The front-end UI for the wait list signup only allows one name&email address regardless of the number of tickets selected, so it seems like the Primary Registrant context would be a better fit anyway.

**Comment by nerrad** [comment]
@sethshoultes if you can, it might be good to research and link to previous discussions on the messaging in Wait-List (there's probably some tickets in codebasehq and in p2).  I think it will be useful to have some context for why things were setup the way they were.  Keep in mind I'm not suggesting that we _won't_ implement the idea proposed here, I just think it is good to evaluate whether doing so will introduce a change in behaviour that might not have been considered yet (and thus we can decide if we're okay with that change in behaviour).
