### ISSUE TITLE
Add feedback on waitlist submission

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/eea-wait-lists#12]
Requested here: https://eventespresso.com/topic/waitlist-cog/#post-287454

If the waitlist submission takes a little while to go through its not obvious that it's working, which apparently is causing some users to submit the form more than once by clicking the button again.

Can we show the ee spinner/cog once the submit button has been clicked?

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

## Steps to Reproduce (for bugs)

Add a waitlist registration and note there's nothing to show the submission is in progress after you submit.

**Comment by joshfeck** [comment]
I'd prefer going forward we use the native WP spinner for things like this. More info here:

https://make.wordpress.org/core/2015/04/23/spinners-and-dismissible-admin-notices-in-4-2/
