### ISSUE TITLE
Fix 'Join wait list' button remaining disabled if reCaptcha is enabled and form validation fails

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/eea-wait-lists#21]
Quick example - https://monosnap.com/file/2Uf9OW2cJpb0shzlRw38didUQ7tk7z

This only happens if you have reCaptcha enabled and try to add a waitlist registration whilst not logged in AND you open up the waitlist form on an event and fail validation by not entering any/all details on the form.

If you are logged in, all good.

If you disable reCaptcha and try again logged out, all good.

**Comment by joshfeck** [comment]
See #20

**Comment by Pebblo** [comment]
@joshfeck this is actually a completely different issue to #20 

The issue here is the submit button remains disabled and you can't submit the form if you've failed validation (left a field empty), #20 happens after you have submitted a valid waitlist form

**Comment by joshfeck** [comment]
Thanks for clarifying the difference here.

**Comment by joshfeck** [comment]
Steps to replicate this issue:

1. Activate reCAPTCHA in Event Espresso > Registration form (you'll need valid keys and you'll set the option to protect the Ticket Selector and set the "Invisible" option)
2) Deactivate the Multi Event Registration add-on (if activated)
3) Activate the Wait List add-on, set up an event and configure the Wait List options to allow for a wait list (set wait list spaces to a value greater than 1) 
4) Create a "Sold Out" condition for the event (e.g. register for enough tickets to hit the reg. limit)
5) While logged out of the site, view the sold out event and click to sign up for the wait list
6) Skip the form fields and click "Join the Wait List" to trigger form validation
7) Now complete the form

The unexpected result is the "Join the Wait List" button stays disabled.

**Comment by hoseinrafiei** [comment]
Hey, I sent a PR to fix this issue. You can find it here: https://github.com/eventespresso/event-espresso-core/pull/2470

**Comment by joshfeck** [comment]
Fixed in https://github.com/eventespresso/event-espresso-core/pull/2470
