### ISSUE TITLE
Fix failing unit tests.

### ISSUE THREAD

**Issue by nerrad** [eventespresso/eea-wait-lists#3]
## Issue Overview

I first noticed this when I was working #2.  It didn't block the merge of #2 because the fails were [already happening in master](https://travis-ci.org/eventespresso/eea-wait-lists/jobs/375011573)

There is a fatal with unit tests:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to EventEspresso\core\domain\DomainBase::__construct() must be an instance of EventEspresso\core\domain\values\FilePath, string given in /tmp/event-espresso-core/core/domain/DomainBase.php:56
```

**Comment by nerrad** [comment]
I've given this a high priority because it seems like the kind of fatal that will happen for users as well.

**Comment by tn3rb** [comment]
plz see: https://github.com/eventespresso/event-espresso-core/pull/386
will mark this invalid when the above PR shows that it fixes this issue.

**Comment by tn3rb** [comment]
closing this because 
- #386 is merged 
- unit tests have been passing: https://travis-ci.org/eventespresso/eea-wait-lists/build
