### ISSUE TITLE
JavaScript Code when Ticket Selector is embed 

### ISSUE THREAD

**Issue by joaovictorangeline** [eventespresso/eea-wait-lists#32]
When you embed an event with the Wait List activated, this JavaScript markup is displayed on the front-end:

`document.getElementById("event-wait-list-24-join-wait-list-btn-submit").onclick = function () { window.open("http://eventespresso.local/events/wait-list-event/?display-wait-list=true"); };`

![CleanShot 2022-07-01 at 7 25 22@2x](https://user-images.githubusercontent.com/102395051/176974058-327f968e-6cfc-4dda-8cda-e4ff20b9b31b.jpg)

**Comment by joaovictorangeline** [comment]
Related ticket: 
https://secure.helpscout.net/conversation/1898807454/906746/

**Comment by hoseinrafiei** [comment]
@joaovictorangeline

Please checkout the https://github.com/eventespresso/event-espresso-core/pull/3934 branch and test the registration form with the new branch. The issue should be fixed now.

<img width="894" alt="Screen Shot 2022-07-05 at 18 57 44" src="https://user-images.githubusercontent.com/29144542/177351580-a136f6c7-fd6f-4c0b-a6e0-00541702bd21.png">
