### ISSUE TITLE
Fix fatal error when previewing HTML receipt

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-wait-lists#7]
This was reported by a beta tester and confirmed by EE staff:

```
Fatal error: Uncaught EventEspresso\core\exceptions\EntityNotFoundException:
The requested entity with Transaction ID="999999" was not found. in /core/db_classes/EE_Registration.class.php:1675 

Stack trace: 
#0 /eea-wait-lists/domain/services/modules/EED_Wait_Lists.module.php(599): EE_Registration->transaction() 
#1 /wp-includes/class-wp-hook.php(286): EED_Wait_Lists::wait_list_checkout_url_query_args(Array, Object(EE_Registration)) 
#2 /wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) 
#3 /core/db_classes/EE_Registration.class.php(939): apply_filters('FHEE__EE_Regist...', Array, Object(EE_Registration)) 
#4 /core/libraries/shortcodes/EE_Primary_Registration_Details_Shortcodes.lib.php(132) 
in /core/db_classes/EE_Registration.class.php on line 1675
```

Steps to replicate: 

1. Activate the Wait Lists add-on
2. Go to edit the Receipt template
3. Verify that the `[EVENT_LIST]` shortcode is within the content of the template
4. View the Preview

**Comment by nerrad** [comment]
@joshfeck can you add what version of EE core and what version of the add-on this is happening with?

**Comment by joshfeck** [comment]
@nerrad the Wait list add-on isn't released yet, so you'll just use current master. Any version of EE4 core will do, but since you can't currently activate the wait list add-on with EE4 core master, you'll need to use a recent release tag to replicate the issue.
